### ISSUE TITLE
the differential time should be "dt_nsec / 1e9"

### ISSUE THREAD

**Issue by orcasdli** [AgileDrones/OptiTrack-Motive-2-Client#7]
The differential time should be `dt_nsec / 1e9` instead of current `dt_nsec * 1e9`
`dt_nsec` is nano second, a very big integer for now. The output velocity  should be converted to `m/s` from current `m/ns`.

**Comment by Winter-Guerra** [comment]
Thanks @orcasdli! It's fixed in master.
